### ISSUE TITLE
Dispatcher Errors

### ISSUE THREAD

**Issue by DavidBrower** [MacLeanElectrical/servicestack-eventstore#9]
When running the integration tests against the embedded EventStore instance in AppVeyor there have been a large number of errors for the types used in the tests:

`ERROR: System.NotImplementedException: Unable to resolve service 'EDTUpdated'
   at ServiceStack.Host.ServiceController.GetService(Type requestType)
   at ServiceStack.Host.ServiceController.ExecuteAsync(Object requestDto, IRequest req)
   at ServiceStack.EventStore.Dispatcher.EventDispatcher.<Dispatch>d__4.MoveNext() in C:\projects\servicestack-eventstore\src\ServiceStack.EventStore\Dispatcher\EventDispatcher.cs:line 49`

Although this is not failing the build it needs to be investigated and fixed.

**Comment by DavidBrower** [comment]
Closed by #8.
